name: CI

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Targeted environment : Prod or Dev (default)'
        required: true
        default: 'Dev'
      Configuration:
        description: 'Type of build : Release or Debug (default)'
        required: true
        default: 'Debug'


jobs:
 Build-EtsDateTime-for-powershell-v5-1:
    runs-on: windows-latest
    #defaults:
      # run: bug de psmodulecache ?
      #   shell: powershell
        # env:
        #   ## Environment variable for step n
        #   VAR_NAME: XXXXXXXXXXXX
        # ## Reference your environment variables
        # run: echo "var :${{env.VAR_NAME}}"
        # run: echo "The API key is:${{secrets.API_KEY}}"

    steps:
      - uses: actions/checkout@v3
      - name : Add 'actionlint' extension for Github Cli
        shell: powershell
        run: |
          gh extension install cschleiden/gh-actionlint

      - name: Set Required repositories
        shell: powershell
        run: |
            $Repositories=@(
              [PsCustomObject]@{
                  name='OttoMatt'
                  publishlocation='https://www.myget.org/F/ottomatt/api/v2/package'
                  sourcelocation='https://www.myget.org/F/ottomatt/api/v2'
              },
              [PsCustomObject]@{
                  name='DevOttoMatt'
                  publishlocation='https://www.myget.org/F/devottomatt/api/v2/package'
                  sourcelocation='https://www.myget.org/F/devottomatt/api/v2'
              }
            )
            $RepositoryNames=[System.Collections.Arraylist]::New()
            Foreach ($Repository in $Repositories)
            {
              $Name=$Repository.Name
              try{
                  $RepositoryNames.Add($Name) > $Null
                  Get-PSRepository $Name -EA Stop >$null
              }catch {
                  if ($_.CategoryInfo.Category -ne 'ObjectNotFound')
                  { throw $_ }
                  else
                  {
                    $Parameters=@{
                        Name=$Name
                        SourceLocation=$Repository.SourceLocation
                        PublishLocation=$Repository.PublishLocation
                        InstallationPolicy='Trusted'
                    }
                    Write-Output "Register repository '$($Repository.Name)'"
                    Register-PSRepository @Parameters
                  }
              }
            }
      - name: Cache modules
        id: psmodulecache
        uses: PSLDA/psmodulecache@v5.0.0-rc
        with:
          modules-to-cache: InvokeBuild::, platyPS::,BuildHelpers, PowerShell-Beautifier,MeasureLocalizedData,Template,OptimizationRules,ParameterSetRules
          shell: powershell
          updatable: "true"
          prefixidentifier: "true"

      - name: Invoke build - mode 'Debug' for 'Dev' environment
        shell: powershell
        env:
            MYGET: ${{ secrets.MYGET }}
            PSGALLERY: ${{ secrets.PSGALLERY }}
        run: |
            .\Build.ps1 -Environnement ${{ github.event.inputs.Environment }} -Release:$('${{ github.event.inputs.Configuration }}' -eq 'Release')

      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v3.1.0
      #   with:
      #     name: EtsDateTime
      #     path:  ${{ github.workspace }}/Release/EtsDateTime

      - name: Publish on Myget
        env:
          MYGET : ${{ secrets.MYGET }}
        shell: powershell
        run: |
          Publish-Module -Path ${{ github.workspace }}/Release/EtsDateTime -Repository 'DevOttoMatt' -NuGetApiKey $env:MYGET -Verbose
          Write-warning "Feed : https://www.myget.org/gallery/devottomatt"
