name: CI

on:
  workflow_dispatch:

jobs:
 Build-EtsDateTime-for-powershell-v5-1:
    runs-on: windows-latest
    #defaults:
      # run: bug de psmodulecache ?
      #   shell: powershell
        # env:
        #   ## Environment variable for step n
        #   VAR_NAME: XXXXXXXXXXXX
        # ## Reference your environment variables
        # run: echo "var :${{env.VAR_NAME}}"
        # run: echo "The API key is:${{secrets.API_KEY}}"

    steps:
      - uses: actions/checkout@v3
      - name: Set Required repositories
        shell: powershell
        run: |
            $Repositories=@(
              [PsCustomObject]@{
                  name='OttoMatt'
                  publishlocation='https://www.myget.org/F/ottomatt/api/v2/package'
                  sourcelocation='https://www.myget.org/F/ottomatt/api/v2'
              },
              [PsCustomObject]@{
                  name='DevOttoMatt'
                  publishlocation='https://www.myget.org/F/devottomatt/api/v2/package'
                  sourcelocation='https://www.myget.org/F/devottomatt/api/v2'
              }
            )
            $RepositoryNames=[System.Collections.Arraylist]::New()
            Foreach ($Repository in $Repositories)
            {
              $Name=$Repository.Name
              try{
                  $RepositoryNames.Add($Name) > $Null
                  Get-PSRepository $Name -EA Stop >$null
              }catch {
                  if ($_.CategoryInfo.Category -ne 'ObjectNotFound')
                  { throw $_ }
                  else
                  {
                    $Parameters=@{
                        Name=$Name
                        SourceLocation=$Repository.SourceLocation
                        PublishLocation=$Repository.PublishLocation
                        InstallationPolicy='Trusted'
                    }
                    Write-Output "Register repository '$($Repository.Name)'"
                    Register-PSRepository @Parameters
                  }
              }
            }

            Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

            #BuildHelpers
            foreach ($module in 'InvokeBuild', 'platyPS', 'PowerShell-Beautifier')
            { Install-Module -name $Module -Repository PSGallery -Scope AllUsers -SkipPublisherCheck -AllowClobber }

            #foreach ($module in 'MeasureLocalizedData','Template','OptimizationRules','ParameterSetRules')
            #{ Install-Module -Repository OttoMatt -Scope AllUsers  -SkipPublisherCheck -AllowClobber }
             #todo Action psmodulecache

      - name: Invoke build - mode 'Debug' for 'Dev' environment
        shell: powershell
        run: |
            .\Build.ps1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: EtsDateTime
          path:  ${{ github.workspace }}/Release/EtsDateTime

      - name: Publish on Myget
        env:
          NUGET_KEY: ${{ secrets.MYGET }}
        shell: powershell
        run: |
          Publish-Module -Path ${{ github.workspace }}/Release/EtsDateTime -Repository 'DevOttoMatt' -NuGetApiKey $env:NUGET_KEY -Verbose
